web:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - db
  hostname: cmpe273assignment1_web_1
  
db:
  hostname: cmpe273assignment1_db_1
  image: mysql:latest
  volumes:
   - ./database:/var/lib/mysql
  environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: assign1
     MYSQL_USER: root
     MYSQL_PASSWORD: root